export EDITOR="nvim"
export PATH="/usr/local/opt/tcl-tk/bin:$PATH"
export PATH="/opt/homebrew/opt/openjdk/bin:$PATH"
export JAVA_HOME=/opt/homebrew/opt/openjdk
export PATH=$PATH:/Users/anand/.spicetify
export NVM_DIR="$HOME/.nvm"
export PATH="$PATH:/Users/anand/Library/Application Support/JetBrains/Toolbox/scripts"
export PATH=$HOME/Developer/flutter/bin:$PATH
export PATH="$HOME/Library/Android/sdk/platform-tools:$PATH"
export ANDROID_HOME="$HOME/Library/Android/sdk"
